# File names for when kamran is kicked
kick_kamran_audio_files:
  - "kamran1.mp3"
  - "kamran2.mp3"
  - "kamran3.mp3"
  - "kamran4.mp3"
  - "kamran5.mp3"
  - "kamran6.mp3"
  - "kamran7.mp3"
  - "kamran8.mp3"

# File names for when caller is kicked
kick_caller_audio_file: "khande_kiri.mp3"

# File names for when kamran is not in channel
celebration_audio_file: "dead.mp3"

# Kamran's unique id
kamran_uid: 336082523010629632

# Chance to kick kamran (between 0 and 1)
kamran_kick_chance: 0.8

# Name of the channel bot will listen to commands and send responses
bot-commands-channel: "bot-commands"

# MongoDB configs
# Password should be put in .env file
mongo-address: "localhost"
mongo-username: "AoKBot"
mongo-db-name: "AttackOnKamran"
